param(
  [int]$RunMinutesPerProfile = 30,
  [string]$PrometheusUrl = "http://localhost:9090",
  [string]$WebappUrl = "http://localhost:8080",
  [string]$DbPath = "Data/processed/nckh_biglogs_training_pool.sqlite",
  [int[]]$Seeds = @(42, 123, 2026),
  [int]$QuickEpochs = 2,
  [int]$NormalUsers = 20,
  [int]$StressUsers = 120,
  [string]$Timestamp = ""
)

$ErrorActionPreference = "Stop"

$timestamp = if ($Timestamp) { $Timestamp } else { Get-Date -Format "yyyyMMdd_HHmmss" }
$dataDir = "Data/testbed/longrun_$timestamp"
$artifactDir = "paper_artifacts/longrun_$timestamp"
$summaryPath = "docs/testbed_longrun_summary_$timestamp.md"
$tableName = "testbed_longrun_$timestamp"

New-Item -ItemType Directory -Force $dataDir, $artifactDir, "docs" | Out-Null

$runStart = [DateTimeOffset]::UtcNow
$profiles = @(
  @{Name="normal"; Users=$NormalUsers; Spawn=5},
  @{Name="gradual"; Users=[int](($NormalUsers + $StressUsers) / 2); Spawn=3},
  @{Name="spike"; Users=$StressUsers; Spawn=50},
  @{Name="stress"; Users=$StressUsers; Spawn=10},
  @{Name="recovery"; Users=$NormalUsers; Spawn=10}
)

docker compose -f testbed/docker-compose.yml up --build -d

foreach ($profile in $profiles) {
  $name = $profile.Name
  $env:LOAD_PROFILE = $name
  $csvPrefix = Join-Path $artifactDir "locust_$name"
  Write-Host "Running long-run profile $name for $RunMinutesPerProfile minutes"
  locust -f testbed/load/locustfile.py --headless `
    --host $WebappUrl `
    --users $profile.Users `
    --spawn-rate $profile.Spawn `
    --run-time "$($RunMinutesPerProfile)m" `
    --csv $csvPrefix
}

$runEnd = [DateTimeOffset]::UtcNow
$startIso = $runStart.UtcDateTime.ToString("o")
$endIso = $runEnd.UtcDateTime.ToString("o")

$rawCsv = Join-Path $dataDir "prometheus_metrics.csv"
$labeledCsv = Join-Path $dataDir "testbed_labeled.csv"
$harmonizedCsv = Join-Path $dataDir "testbed_harmonized.csv"

python -m src.tools.collect_prometheus_metrics `
  --prometheus-url $PrometheusUrl `
  --start $startIso `
  --end $endIso `
  --output $rawCsv `
  --load-profile "longrun_mixed"

python -m src.tools.label_testbed_congestion `
  --input $rawCsv `
  --output $labeledCsv

python -m src.tools.prepare_testbed_dataset `
  --input $labeledCsv `
  --output $harmonizedCsv `
  --db-path $DbPath `
  --table $tableName

$seedArgs = $Seeds | ForEach-Object { "$_" }
python -m src.tools.run_paper_experiments `
  --db-path $DbPath `
  --table $tableName `
  --testbed-csv $labeledCsv `
  --raw-testbed-csv $rawCsv `
  --output-dir $artifactDir `
  --quick-epochs $QuickEpochs `
  --seeds $seedArgs

$summary = [ordered]@{
  timestamp = $timestamp
  run_minutes_per_profile = $RunMinutesPerProfile
  started_utc = $startIso
  ended_utc = $endIso
  data_dir = $dataDir
  artifact_dir = $artifactDir
  raw_csv = $rawCsv
  labeled_csv = $labeledCsv
  harmonized_csv = $harmonizedCsv
  sqlite_db = $DbPath
  sqlite_table = $tableName
  summary_path = $summaryPath
}

$summary | ConvertTo-Json -Depth 4 | Set-Content -Encoding UTF8 (Join-Path $dataDir "longrun_manifest.json")

$summaryText = @(
  "# Testbed Long-Run Summary",
  "",
  "Timestamp: $timestamp",
  "",
  "This file is a placeholder generated by testbed/run_longrun_pipeline.ps1.",
  "The measured row counts, label distribution, artifact scan, and model metrics are filled by the coding agent after reading the generated files.",
  "",
  "- Run minutes per profile: $RunMinutesPerProfile",
  "- Started UTC: $startIso",
  "- Ended UTC: $endIso",
  "- Data directory: $dataDir",
  "- Artifact directory: $artifactDir",
  "- SQLite table: $tableName"
) -join "`n"
$summaryText | Set-Content -Encoding UTF8 $summaryPath

Write-Host "LONGRUN_TIMESTAMP=$timestamp"
Write-Host "LONGRUN_DATA_DIR=$dataDir"
Write-Host "LONGRUN_ARTIFACT_DIR=$artifactDir"
Write-Host "LONGRUN_SUMMARY=$summaryPath"
