from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd


@dataclass
class SourceCandidate:
    source_name: str
    source_url: str
    license_terms: str
    local_sample: str
    notes: str


SOURCES = [
    # --- REAL traces downloaded from Zenodo (CC-BY 4.0) ---
    SourceCandidate(
        "Alibaba Cluster Trace (2018, derived from Zenodo)",
        "https://zenodo.org/records/14564935",
        "CC-BY 4.0",
        "Data/real/alibaba_cluster_trace/machine_usage_days_1_to_8_grouped_300_seconds.csv",
        "REAL DATA (derived): Processed from Alibaba cluster-trace-v2018 by third party. "
        "2243 rows, columns: cpu_util_percent, mem_util_percent, net_in, net_out, disk_io_percent. "
        "MD5: 6c2312c01f1c4dc4b6863c4402976dee. Different schema from synthetic files.",
    ),
    SourceCandidate(
        "Google Cluster Trace (2019, derived from Zenodo)",
        "https://zenodo.org/records/14564935",
        "CC-BY 4.0",
        "Data/real/google_cluster_trace/instance_usage_grouped_300_seconds_month.csv",
        "REAL DATA (derived): Processed from Google 2019 cluster traces via BigQuery by third party. "
        "8064 rows, columns: avg_cpu, avg_mem, avg_assigned_mem, avg_cycles_per_instruction. "
        "MD5: 08d31b15f3203cd40407bdfb6ca902ea. Different schema from synthetic files.",
    ),
    SourceCandidate(
        "Azure VM Trace (v2, derived from Zenodo)",
        "https://zenodo.org/records/14564935",
        "CC-BY 4.0",
        "Data/real/azure_vm_trace/vm_cpu_readings_month_aggregated_cpu_mem.csv",
        "REAL DATA (derived): Processed from Azure Public Dataset v2 by third party. "
        "8640 rows, columns: timestamp (seconds), cpu_usage, assigned_mem. "
        "MD5: b14d5002a7d2f7e0033a0deae63d2ced. Different schema from synthetic files.",
    ),
    # --- SYNTHETIC fallbacks (generated, not real traces) ---
    SourceCandidate(
        "Synthetic ClusterWorkload (Alibaba-style, generated)",
        "N/A — generated by SyntheticDataGenerator in src/utils/legacy/data_generator.py",
        "Internal synthetic data; no real Alibaba trace was available locally.",
        "Data/Synthetic_ClusterWorkload_AlibabaStyle_v1.csv",
        "SYNTHETIC FALLBACK: Generated with sin-wave + Gaussian noise + anomaly injection. "
        "NOT a real Alibaba cluster trace. Named to indicate the workload pattern it emulates. "
        "For real Alibaba data, see Data/real/alibaba_cluster_trace/.",
    ),
    SourceCandidate(
        "Synthetic ClusterWorkload (Google-style, generated)",
        "N/A — generated by SyntheticDataGenerator in src/utils/legacy/data_generator.py",
        "Internal synthetic data; no real Google Cluster trace was available locally.",
        "Data/Synthetic_ClusterWorkload_GoogleStyle_v1.csv",
        "SYNTHETIC FALLBACK: Generated with sin-wave + Gaussian noise + anomaly injection. "
        "NOT a real Google Cluster trace. For real Google data, see Data/real/google_cluster_trace/.",
    ),
    SourceCandidate(
        "Synthetic VMWorkload (Azure-style, generated)",
        "N/A — generated by SyntheticDataGenerator in src/utils/legacy/data_generator.py",
        "Internal synthetic data; no real Azure VM trace was available locally.",
        "Data/Synthetic_VMWorkload_AzureStyle_v1.csv",
        "SYNTHETIC FALLBACK: Generated with sin-wave + Gaussian noise + anomaly injection. "
        "NOT a real Azure VM trace. For real Azure data, see Data/real/azure_vm_trace/.",
    ),
    SourceCandidate(
        "Synthetic FastStorageWorkload (Bitbrains-style, generated)",
        "N/A — generated by SyntheticDataGenerator in src/utils/legacy/data_generator.py",
        "Internal synthetic data; no real Bitbrains trace was available locally.",
        "Data/Synthetic_FastStorageWorkload_BitbrainsStyle_v1.csv",
        "SYNTHETIC FALLBACK: Generated with sin-wave + Gaussian noise + anomaly injection. "
        "NOT a real Bitbrains trace. GWA-T-12 site was unreachable.",
    ),
    SourceCandidate(
        "Synthetic CloudMonitoringWorkload (AWS-style, generated)",
        "N/A — generated by SyntheticDataGenerator in src/utils/legacy/data_generator.py",
        "Internal synthetic data; no public AWS CloudWatch trace dataset exists.",
        "Data/Synthetic_CloudMonitoring_Workload_v1.csv",
        "SYNTHETIC FALLBACK: Generated with sin-wave + Gaussian noise + anomaly injection. "
        "No official 'AWS CloudWatch Trace' public dataset exists. This is a synthetic emulation.",
    ),
]


def collect_local_sources(repo_root: str | Path, include_old_bitbrains_train: bool = False) -> tuple[pd.DataFrame, list[dict], list[dict]]:
    repo = Path(repo_root)
    inventory = []
    failures = []
    frames = []
    for src in SOURCES:
        path = repo / src.local_sample
        if not path.exists():
            failures.append(
                {
                    "source_name": src.source_name,
                    "source_url": src.source_url,
                    "problem": f"Local sample not found: {src.local_sample}",
                }
            )
            continue
        if "Bitbrains" in src.source_name and not include_old_bitbrains_train:
            continue
        try:
            df = pd.read_csv(path)
            frames.append(df.assign(__source_name=src.source_name, __source_path=str(path)))
            inventory.append(
                {
                    "source_name": src.source_name,
                    "source_url": src.source_url,
                    "license_terms": src.license_terms,
                    "downloaded_file_path": str(path),
                    "raw_rows": len(df),
                    "selected_rows": len(df),
                    "columns": ", ".join(map(str, df.columns)),
                    "timestamp_column": "timestamp" if "timestamp" in {c.lower() for c in df.columns} else "",
                    "machine_service_id_column": "not present in local sample",
                    "metrics_available": ", ".join([c for c in df.columns if c.lower() != "timestamp"]),
                    "problems_limitations": src.notes,
                }
            )
        except Exception as exc:
            failures.append({"source_name": src.source_name, "source_url": src.source_url, "problem": str(exc)})
    combined = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    return combined, inventory, failures
